FEC-12555 Player sample iOS updated deployment target to 12.0
kaltura/kaltura-player-ios-samples pull request #29
Opened 2022-09-13 11:12 UTC by chausov

FEC-12555
Player sample iOS updated deployment target to 12.0

2022-09-14 13:38 UTC, x-NR-x commented
What about the BasicSample?
Is this only for the iOS samples or also needed for the tvOS samples?

2022-09-14 13:51 UTC, chausov commented
> What about the BasicSample?
> Is this only for the iOS samples or also needed for the tvOS samples?

In Basic we do not have cast implementation so it is not required to set it to 12.0

2022-09-15 09:19 UTC, x-NR-x commented
> > What about the BasicSample?
> > Is this only for the iOS samples or also needed for the tvOS samples?
> 
> In Basic we do not have cast implementation so it is not required to set it to 12.0 Same with tvOS.

In that case, because it was done only for the cast, that is ok.
Next time please mention it here and/or the ticket.

2022-09-15 09:28 UTC, x-NR-x requested changes

2022-09-15 09:28 UTC, x-NR-x commented on OTTSample/OTTSample.xcodeproj/project.pbxproj
> +				MACOSX_DEPLOYMENT_TARGET = 12.0;
Why was this added?
The sample is only for iOS.
Please remove.

2022-09-15 09:28 UTC, x-NR-x commented on OTTSample/OTTSample.xcodeproj/project.pbxproj
> +				TVOS_DEPLOYMENT_TARGET = 12.0;
Why was this added?
The sample is only for iOS.
Please remove.

2022-09-15 09:28 UTC, x-NR-x commented on OTTSample/OTTSample.xcodeproj/project.pbxproj
> +				MACOSX_DEPLOYMENT_TARGET = 12.0;
Why was this added?
The sample is only for iOS.
Please remove.

2022-09-15 09:28 UTC, x-NR-x commented on OTTSample/OTTSample.xcodeproj/project.pbxproj
> +				TVOS_DEPLOYMENT_TARGET = 12.0;
Why was this added?
The sample is only for iOS.
Please remove.

2022-09-15 09:28 UTC, x-NR-x commented on OVPSample/OVPSample.xcodeproj/project.pbxproj
> +				MACOSX_DEPLOYMENT_TARGET = 12.0;
Why was this added?
The sample is only for iOS.
Please remove.

2022-09-15 09:28 UTC, x-NR-x commented on OVPSample/OVPSample.xcodeproj/project.pbxproj
> +				TVOS_DEPLOYMENT_TARGET = 12.0;
Why was this added?
The sample is only for iOS.
Please remove.

2022-09-15 09:28 UTC, x-NR-x commented on OVPSample/OVPSample.xcodeproj/project.pbxproj
> +				MACOSX_DEPLOYMENT_TARGET = 12.0;
Why was this added?
The sample is only for iOS.
Please remove.

2022-09-15 09:28 UTC, x-NR-x commented on OVPSample/OVPSample.xcodeproj/project.pbxproj
> +				TVOS_DEPLOYMENT_TARGET = 12.0;
Why was this added?
The sample is only for iOS.
Please remove.

2022-10-26 07:06 UTC, giladna approved these changes

2022-10-26 12:33 UTC, x-NR-x approved these changes

2022-10-26 13:54 UTC, merged